### ISSUE TITLE
Design: Create Postcard Design

### ISSUE THREAD

**Issue by ravenac95** [PhillyVoteByMail/phillyvotebymail#11]
We need to design and setup postcards to be delivered. 

* [ ] Design: Create a postcard design
   - See ClickSend docs: [Postcard template](https://help.clicksend.com/article/ysyql7bsr1-postcard-template). 
* [ ] Design: Add the PDF containing the postcard design to github repo
* [ ] Engineering: Setup Postcard Design's URL in deployment configuration

**Comment by conorgil** [comment]
> Design: Upload the postcard design to clicksend
> Engineering: Setup Postcard Design's URL in deployment configuration

Looking over the ClickSend API [here](https://developers.clicksend.com/docs/rest/v3/#send-postcard), it sounds like we are not able to upload our design to a ClickSend server for long-term storage. Uploads to their servers are deleted after 10 minutes. However, we can provide a URL to a publicly accessible file that they will download (and cache, I assume).

The easiest thing to do is probably to upload the postcard design assets to github and then just use the URL to the raw file in the ClickSend API call.
